blank_issues_enabled: false
contact_links:
  - name: Snotchy on Linktree
    url: https://linktr.ee/Snotchy
    about: Chat with the community for general questions and support.
  - name: Shelly's Site
    url: https://www.seafoam-labs.org/
    about: Our site with documentation and more.
 
